# nixpacks.toml

[phases.setup]
# Menambahkan library sistem yang dibutuhkan oleh Puppeteer/Chromium
aptPkgs = [
  "chromium",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgtk-3-0",
  "libgbm-dev",
  "libasound2t64",  # <-- INI DIA PERUBAHANNYA
  "libgobject-2.0-0"
]